packaging_format = 2

id = "tracim"
name = "Tracim"
description.en = "Collaborative platform intended for team collaboration"
description.fr = "Plateforme collaborative destiné à la collaboration en équipe"

version = "4.6.1~ynh2"

maintainers = []

[upstream]
license = "AGPL-3.0-or-later,LGPL-3.0-or-later,CC-BY-SA-2.5,MIT"
website = "https://www.tracim.fr"
demo = "https://www.algoo.fr/fr/tracim/demo"
admindoc = "https://public-community.tracim.fr/ui/workspaces/143/contents"
code = "https://github.com/tracim/tracim"

[integration]
yunohost = ">= 11.2"
architectures = ["amd64"]
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "1500M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en", "pt", "de", "ar"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
        [resources.sources.main]
        url = "https://github.com/tracim/tracim/archive/refs/tags/release_04.06.01.tar.gz"
        sha256 = "aad538f9de14fa66b78dc062b1e873bf8d7998dc293de026cc01f38624133932"
        autoupdate.strategy = "latest_github_release"
        autoupdate.version_regex = "^release_(.*)$"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["depot", "radicale_storage"]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "ffmpeg, xvfb, inkscape, libreoffice, postgresql, ghostscript, git, imagemagick, iproute2, libfile-mimeinfo-perl, libimage-exiftool-perl, webp, libmagic1, locales, poppler-utils, python3, python3-pip, uwsgi, uwsgi-plugin-python3, supervisor, build-essential, libjpeg-dev, libmagickwand-dev, libpq-dev, python3-dev, python3-venv"

    extras.yarn.repo = "deb https://dl.yarnpkg.com/debian/ stable main"
    extras.yarn.key = "https://dl.yarnpkg.com/debian/pubkey.gpg"
    extras.yarn.packages = "yarn"

    [resources.database]
    type = "postgresql"
