#:schema https://raw.githubusercontent.com/YunoHost/apps/master/schemas/manifest.v2.schema.json

packaging_format = 2

id = "tracim"
name = "Tracim"
description.en = "Collaborative platform intended for team collaboration"
description.fr = "Plateforme collaborative destiné à la collaboration en équipe"

version = "04.11.01~ynh1"

maintainers = []

[upstream]
license = "AGPL-3.0-or-later,LGPL-3.0-or-later,CC-BY-SA-2.5,MIT"
website = "https://www.tracim.fr"
demo = "https://www.algoo.fr/fr/tracim/demo"
admindoc = "https://public-community.tracim.fr/ui/workspaces/143/contents"
code = "https://github.com/tracim/tracim"

[integration]
yunohost = ">= 11.2.30"
architectures = ["amd64"]
multi_instance = true

ldap = false

sso = false

disk = "50M"
ram.build = "1500M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.language]
    ask.en = "Choose the application language"
    ask.fr = "Choisissez la langue de l'application"
    type = "select"
    choices = ["fr", "en", "pt", "de", "ar"]
    default = "fr"

    [install.admin]
    type = "user"

    [install.password]
    type = "password"

[resources]
        [resources.sources.main]
        url = "https://github.com/tracim/tracim/archive/refs/tags/release_04.11.01.tar.gz"
        sha256 = "9c7550d72d47902a04348e302df700c065a44b81f49d8de1d36ddc7cf70ae7e9"
        autoupdate.strategy = "latest_github_release"
        autoupdate.version_regex = "^release_(.*)$"

    [resources.ports]

    [resources.system_user]

    [resources.install_dir]

    [resources.data_dir]
    subdirs = ["depot", "radicale_storage"]

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = [
        "ffmpeg",
        "xvfb",
        "inkscape",
        "libreoffice",
        "postgresql",
        "ghostscript",
        "git",
        "imagemagick",
        "iproute2",
        "libfile-mimeinfo-perl",
        "libimage-exiftool-perl",
        "webp",
        "libmagic1",
        "locales",
        "poppler-utils",
        "python3",
        "python3-pip",
        "uwsgi",
        "uwsgi-plugin-python3",
        "supervisor",
        "build-essential",
        "libjpeg-dev",
        "libmagickwand-dev",
        "libpq-dev",
        "python3-dev",
        "python3-venv",
        "redis-server",
    ]

    [resources.database]
    type = "postgresql"
