#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_exec_warn_less yunohost service status uwsgi >/dev/null
then
	ynh_script_progression --message="Removing uwsgi service integration..."
	yunohost service remove uwsgi
fi
if ynh_exec_warn_less yunohost service status supervisor >/dev/null
then
	ynh_script_progression --message="Removing supervisor service integration..."
	yunohost service remove supervisor
fi

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression --message="Stopping and removing the systemd service..."

# Remove the dedicated systemd config
ynh_remove_supervisor_config --service="$app"

ynh_secure_remove --file="/etc/uwsgi/apps-enabled/$app-web.ini"
ynh_secure_remove --file="/etc/uwsgi/apps-available/$app-web.ini"
ynh_secure_remove --file="/etc/uwsgi/apps-enabled/$app-webdav.ini"
ynh_secure_remove --file="/etc/uwsgi/apps-available/$app-webdav.ini"
ynh_secure_remove --file="/etc/uwsgi/apps-enabled/$app-caldav.ini"
ynh_secure_remove --file="/etc/uwsgi/apps-available/$app-caldav.ini"
ynh_systemd_action --service_name="uwsgi" --action="restart"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression --message="Removing NGINX web server configuration..."

ynh_remove_nginx_config

#=================================================
# REMOVE DEPENDENCIES
#=================================================
ynh_script_progression --message="Removing dependencies..."

# Remove metapackage and its dependencies
ynh_redis_remove_db "$redis_db"
ynh_remove_nodejs

#=================================================
# REMOVE VARIOUS FILES
#=================================================
ynh_script_progression --message="Removing various files..."

# Remove the log files
ynh_secure_remove --file="/var/log/uwsgi/app/$app-web.log"
ynh_secure_remove --file="/var/log/uwsgi/app/$app-webdav.log"
ynh_secure_remove --file="/var/log/uwsgi/app/$app-caldav.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression --message="Removal of $app completed"
