#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# STANDARD REMOVE
#=================================================
# REMOVE SERVICE INTEGRATION IN YUNOHOST
#=================================================

# Remove the service from the list of services known by YunoHost (added from `yunohost service add`)
if ynh_hide_warnings yunohost service status uwsgi >/dev/null
then
	ynh_script_progression "Removing uwsgi service integration..."
	yunohost service remove uwsgi
fi
if ynh_hide_warnings yunohost service status supervisor >/dev/null
then
	ynh_script_progression "Removing supervisor service integration..."
	yunohost service remove supervisor
fi

#=================================================
# STOP AND REMOVE SERVICE
#=================================================
ynh_script_progression "Stopping and removing the systemd service..."

# Remove the dedicated systemd config
ynh_remove_supervisor_config

ynh_safe_rm "/etc/uwsgi/apps-enabled/$app-web.ini"
ynh_safe_rm "/etc/uwsgi/apps-available/$app-web.ini"
ynh_safe_rm "/etc/uwsgi/apps-enabled/$app-webdav.ini"
ynh_safe_rm "/etc/uwsgi/apps-available/$app-webdav.ini"
ynh_safe_rm "/etc/uwsgi/apps-enabled/$app-caldav.ini"
ynh_safe_rm "/etc/uwsgi/apps-available/$app-caldav.ini"
ynh_systemctl --service="uwsgi" --action="restart"

#=================================================
# REMOVE NGINX CONFIGURATION
#=================================================
ynh_script_progression "Removing NGINX web server configuration..."

# Remove the dedicated NGINX config
ynh_config_remove_nginx

#=================================================
# REMOVE DEPENDENCIES
#=================================================
#REMOVEME? ynh_script_progression "Removing dependencies..."

# Remove metapackage and its dependencies
ynh_redis_remove_db "$redis_db"
ynh_nodejs_remove

#=================================================
# SPECIFIC REMOVE
#=================================================
# REMOVE VARIOUS FILES
#=================================================
ynh_script_progression "Removing various files..."

# Remove the log files
ynh_safe_rm "/var/log/uwsgi/app/$app-web.log"
ynh_safe_rm "/var/log/uwsgi/app/$app-webdav.log"
ynh_safe_rm "/var/log/uwsgi/app/$app-caldav.log"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Removal of $app completed"
